name: onboard-snap
version: '1.0'
summary: On-screen keyboard for Linux
description: |
  Onboard is an on-screen keyboard useful for touch devices or accessibility needs.
grade: stable
confinement: strict

apps:
  onboard:
    command: onboard

parts:
  install-pip:
    plugin: nil
    stage-packages:
      - python3-distutils
    build-packages:
      - wget
    override-build: |
      wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py
      python3 get-pip.py pip==20.3.3
    prime:
      - get-pip.py
    after:
      - python3

  onboard:
    plugin: python
    source: https://code.launchpad.net/onboard
    source-type: bzr
    build-packages:
      - build-essential
      - fakeroot
