name: onboard-snap
version: '1.0'
summary: On-screen keyboard for Linux
description: |
  Onboard is an on-screen keyboard useful for touch devices or accessibility needs.
grade: stable
confinement: strict

apps:
  onboard:
    command: onboard

parts:
  onboard:
    plugin: python3
    source: https://code.launchpad.net/onboard
    source-type: bzr
    build-packages:
          - python3
          - debuild
