name: onboard-snap
version: '1.0'
summary: On-screen keyboard for Linux
description: |
  Onboard is an on-screen keyboard useful for touch devices or accessibility needs.
grade: stable
confinement: strict

apps:
  onboard:
    command: onboard

parts:
  onboard:
    plugin: nil
    source: https://launchpad.net/onboard
    source-type: bzr
    override-build: |
    sudo apt-get build-dep onboard
        sudo apt-get install devscripts
        bzr branch lp:onboard
        cd onboard

        debuild binary

        sudo dpkg -i ../onboard*.deb
