name: onboard-snap
version: '1.0'
summary: On-screen keyboard for Linux
description: |
  Onboard is an on-screen keyboard useful for touch devices or accessibility needs.
grade: stable
confinement: strict

apps:
  onboard:
    command: onboard

parts:
  onboard:
    plugin: nil
    source: https://code.launchpad.net/onboard
    source-type: bzr
    build-packages:
      - debhelper-compat (= 12)
      - dh-python
      - libcanberra-dev
      - libdconf-dev (>= 0.12.0)
      - libgtk-3-dev
      - libhunspell-dev
      - libudev-dev
      - libwayland-dev
      - libxkbfile-dev
      - libxtst-dev
      - python3-dev
      - python3-cairo
      - python3-distutils-extra
      - python3-gi
      - build-essential
      - fakeroot
      - python3
