name: onboard-snap
version: '1.0'
summary: On-screen keyboard for Linux
description: |
  Onboard is an on-screen keyboard useful for touch devices or accessibility needs.
grade: stable
confinement: strict

apps:
  onboard:
    command: onboard

parts:
  onboard:
    plugin: nil
    source: https://bazaar.launchpad.net/~onboard/onboard/trunk/files
    source-type: bzr
    build-packages:
          - python3
    override-build: |
      sudo apt-get update
      sudo apt-get build-dep -y onboard
      sudo apt-get install -y devscripts
      bzr branch lp:onboard
      cd onboard
      debuild binary
